from typing import TypedDict, List, Optional, Dict
from src.db.schema import CodeEntity, DocEntity

class AgentState(TypedDict):
    """
    The shared memory of the Agent Swarm.
    LangGraph passes this dictionary between nodes.
    """
    
    # --- INPUTS ---
    project_name: str
    target_file: str            # The specific file we are documenting
    code_context: List[CodeEntity] # The "Truth" from the AST
    doc_requirements: List[DocEntity] # The "Requirements" from the PRD
    
    # --- PROCESSING ---
    drift_report: Dict          # The output from Phase 2 Drift Engine
    critique_count: int         # How many times have we looped?
    max_revisions: int          # Safety limit (e.g., 3 loops)
    
    # --- OUTPUTS ---
    current_draft: str          # The text generated by the Stylist
    critique_feedback: Optional[str] # Why the Critic rejected it
    is_compliant: bool          # If True, we exit the loop